name: flutter_url_get_preview
description: Ler url y generar vista previa.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.8.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  rxdart: ^0.27.2
  equatable: ^2.0.0
  html: ^0.15.0
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.2
  webview_flutter: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
